version: '3'
services:
    web:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./:/app"
        env_file:
            - ../db.env
        depends_on:
            - database
    database:
        image: postgres:alpine
        env_file:
            - ../db.env
        volumes:
            - ../db:/var/lib/postgresql/data/
volumes:
    db:
